ALTER TABLE providers ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE providers ADD COLUMN IF NOT EXISTS hourly_rate DECIMAL(10, 2);
ALTER TABLE providers ADD COLUMN IF NOT EXISTS referral_code VARCHAR(50);